# keys
OPENAI_API_KEY = "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"
WOLFRAM_API_KEY = "TT3P62-W479LAP7E3"


# hololens values
HOLOLENS_IP_ADDRESS = "192.168.0.114"
MIXED_REALITY_DEVICE_PORTAL_USERNAME = "acelab"
MIXED_REALITY_DEVICE_PORTAL_PASSWORD = "ace1ace!"
HOLOLENS_URL = "http://"+MIXED_REALITY_DEVICE_PORTAL_USERNAME + \
    ":"+MIXED_REALITY_DEVICE_PORTAL_PASSWORD+"@"+HOLOLENS_IP_ADDRESS


YOLO_V7_MODEL_PATH = "custom_models/yolov7.pt"
YOLO_V7_TINY_MODEL_PATH = "custom_models/yolov7.pt"


# session states
SESSION_STATE_LAUNCH = "SESSION_STATE_LAUNCH"
SESSION_STATE_MAIN = "SESSION_STATE_MAIN"
SESSION_STATE_ONGOING_LESSON = "SESSION_STATE_ONGOING_LESSON"


# Zed mini and Hololens 2 Alignment
DELTA_X = 0
DELTA_Y = 0
DELTA_Z = 0
