# keys
OPENAI_API_KEY = "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"
WOLFRAM_API_KEY = "TT3P62-W479LAP7E3"
WIT_ACCESS_TOKEN = "UMSUGGCXUXBRUWVSU2M7PY7O2QFK7EGD"



# hololens values
HOLOLENS_IP_ADDRESS = "192.168.0.76"
MIXED_REALITY_DEVICE_PORTAL_USERNAME = "acelab"
MIXED_REALITY_DEVICE_PORTAL_PASSWORD = "ace1ace!"
HOLOLENS_URL = "http://"+MIXED_REALITY_DEVICE_PORTAL_USERNAME + \
    ":"+MIXED_REALITY_DEVICE_PORTAL_PASSWORD+"@"+HOLOLENS_IP_ADDRESS


YOLO_V7_MODEL_PATH = "custom_models/yolov7.pt"
YOLO_V7_TINY_MODEL_PATH = "custom_models/yolov7.pt"


# session states
SESSION_STATE_LAUNCH = "SESSION_STATE_LAUNCH"
SESSION_STATE_EXPLORE = "SESSION_STATE_EXPLORE"
SESSION_STATE_INITIATING_LESSON = "SESSION_STATE_INITIATING_LESSON"
SESSION_STATE_LESSON_INITIATED = "SESSION_STATE_LESSON_INITIATED"
SESSION_STATE_DISCONNECTED = "SESSION_STATE_DISCONNECTED"

# CLIENT_SERVER PROTOCOL
DATA_TYPE = "DATA_TYPE"
DATA_VALUE = "DATA_VALUE"
ENVIRONMENT_OJBECTS_UPDATE = "ENVIRONMENT_OJBECTS_UPDATE"
INITIATE_LESSON_REQUEST = "INITIATE_LESSON_REQUEST"
LESSON_INIT_INFO = "LESSON_INIT_INFO"
SPEECH_SENTENCE_SPOKEN = "SPEECH_SENTENCE_SPOKEN"
BUTTON_PRESSED = "BUTTON_PRESSED"
REQUEST_ENV_INFO_UPDATE = "REQUEST_ENV_INFO_UPDATE"
SHOW_3D_MODEL = "SHOW_3D_MODEL"
SET_USER_PREFERENCES = "SET_USER_PREFERENCES"
GAZE_INPUT = "GAZE_INPUT"
MARS_MOVED_LISTENER = "MARS_MOVED_LISTENER"
MARS_MOVED_UPDATE_POSITION = "MARS_MOVED_UPDATE_POSITION"
# Zed mini and Hololens 2 Alignment
DELTA_X = 0.3
DELTA_Y = 0.2
DELTA_Z = -0.5


# VOICE WIT INTENTS
load_3d_model = "load_3d_model"
modify_user_preferences = "modify_user_preferences"
descriptive_query = "descriptive_query"
fact_query = "fact_query"
