//export const SERVER_IP = "http://192.168.0.117:8000";
export const SERVER_IP = "http://localhost:8000";
export const TAGS = [
  "Addition",
  "Subtraction",
  "Multiplication",
  "Division",
  "Fractions",
  "Decimals",
  "Geometry",
  "Algebra",
  "Trigonometry",
  "Calculus",
  "Probability",
  "Statistics",
  "Measurement",
  "Time",
  "Money",
  "Temperature",
  "Energy",
  "Force",
  "Motion",
  "Sound",
  "Light",
  "Magnetism",
  "Electricity",
  "Chemistry",
  "Biology",
  "Physics",
  "Earth science",
  "Astronomy",
  "History",
  "Geography",
  "Political science",
  "Economics",
  "Sociology",
  "Psychology",
  "Anthropology",
  "Philosophy",
  "Ethics",
  "Logic",
  "Epistemology",
  "Metaphysics",
  "Aesthetics",
  "Language arts",
  "Literature",
  "Reading",
  "Writing",
  "Grammar",
  "Vocabulary",
  "Spelling",
  "Phonics",
  "Social studies",
  "Civics",
  "Government",
  "Culture",
  "Religion",
  "Art",
  "Music",
  "Theater",
  "Dance",
  "Physical education",
  "Health",
  "Nutrition",
  "Wellness",
  "Safety",
  "Personal finance",
  "Business",
  "Marketing",
  "Management",
  "Leadership",
  "Entrepreneurship",
  "Innovation",
  "Technology",
  "Computer science",
  "Programming",
  "Web development",
  "Cybersecurity",
  "Data science",
  "Machine learning",
  "Artificial intelligence",
  "Robotics",
  "Engineering",
  "Architecture",
  "Design",
  "Fashion",
  "Culinary arts",
  "Hospitality",
  "Travel",
  "Sports",
  "Recreation",
  "Outdoor education",
  "Environmental science",
  "Sustainability",
  "Humanitarianism",
  "Volunteerism",
  "Advocacy",
  "Activism",
  "Community service",
  "Interpersonal skills",
  "Career development",
  "Self-improvement",
  "Life skills",
];
export const object_data = [
  "airplane",
  "apple",
  "backpack",
  "banana",
  "baseball bat",
  "baseball glove",
  "bear",
  "bed",
  "bench",
  "bicycle",
  "bird",
  "boat",
  "book",
  "bottle",
  "bowl",
  "broccoli",
  "bus",
  "cake",
  "car",
  "carrot",
  "cat",
  "cell phone",
  "chair",
  "clock",
  "cow",
  "cup",
  "dog",
  "donut",
  "dining table",
  "elephant",
  "fire hydrant",
  "fork",
  "frisbee",
  "giraffe",
  "handbag",
  "hair drier",
  "horse",
  "hot dog",
  "keyboard",
  "kite",
  "knife",
  "laptop",
  "microwave",
  "motorcycle",
  "mouse",
  "orange",
  "oven",
  "parking meter",
  "person",
  "pizza",
  "potted plant",
  "refrigerator",
  "remote",
  "scissors",
  "sheep",
  "sink",
  "skateboard",
  "skis",
  "snowboard",
  "spoon",
  "sports ball",
  "stop sign",
  "suitcase",
  "surfboard",
  "teddy bear",
  "tennis racket",
  "tie",
  "toaster",
  "toilet",
  "toothbrush",
  "traffic light",
  "train",
  "truck",
  "tv",
  "umbrella",
  "vase",
  "wine glass",
  "zebra",
];
